package editorial

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"time"
	"unicode/utf8"

	"github.com/luminbuddy/luminbuddy-writing-agent-v2/internal/engine"
)

// ArtifactRecorder records writing process artifacts from ExecutionContext
// to the editorial_artifacts table, providing full traceability of the
// writing pipeline's intermediate products.
type ArtifactRecorder struct {
	store *Store
}

// NewArtifactRecorder creates a new ArtifactRecorder.
func NewArtifactRecorder(store *Store) *ArtifactRecorder {
	return &ArtifactRecorder{store: store}
}

// RecordWritingArtifacts records all intermediate products from a completed
// (or failed) writing session into editorial_artifacts.
//
// Each artifact captures a specific stage of the writing pipeline:
//   - source_pack:      Full search results after relevance filtering
//   - research_brief:   Compressed research context + writing task info
//   - outline:          Article outline (guided mode only)
//   - draft:            Initial article generated by WriteStep
//   - review_report:    Post-review quality assessment
//   - revised_draft:    Article after AutoFix (if applied)
//   - memory_context:   Injected user preference memories (if any)
//
// All artifacts are auto-approved (status='approved') since they are
// objective records of what happened during the writing process.
func (r *ArtifactRecorder) RecordWritingArtifacts(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	if r.store == nil || taskID == "" || execCtx == nil {
		return nil
	}

	var errs []error

	// 1. Source pack — full search results
	if len(execCtx.SearchResults) > 0 {
		if err := r.recordSourcePack(ctx, execCtx, taskID); err != nil {
			slog.Warn("artifact recorder: failed to record source_pack", "error", err, "trace_id", execCtx.TraceID)
			errs = append(errs, err)
		}
	}

	// 2. Research brief — compressed context + writing task metadata
	if execCtx.CompressedContext != "" || execCtx.WritingTask != nil {
		if err := r.recordResearchBrief(ctx, execCtx, taskID); err != nil {
			slog.Warn("artifact recorder: failed to record research_brief", "error", err, "trace_id", execCtx.TraceID)
			errs = append(errs, err)
		}
	}

	// 3. Outline (guided mode only)
	if execCtx.Outline != nil {
		if err := r.recordOutline(ctx, execCtx, taskID); err != nil {
			slog.Warn("artifact recorder: failed to record outline", "error", err, "trace_id", execCtx.TraceID)
			errs = append(errs, err)
		}
	}

	// 4. Draft — the article (before auto_fix, if applicable)
	if execCtx.Article != "" {
		if err := r.recordDraft(ctx, execCtx, taskID); err != nil {
			slog.Warn("artifact recorder: failed to record draft", "error", err, "trace_id", execCtx.TraceID)
			errs = append(errs, err)
		}
	}

	// 5. Review report
	if execCtx.ReviewResult != nil {
		if err := r.recordReviewReport(ctx, execCtx, taskID); err != nil {
			slog.Warn("artifact recorder: failed to record review_report", "error", err, "trace_id", execCtx.TraceID)
			errs = append(errs, err)
		}
	}

	// 6. Revised draft (if auto_fix was applied)
	if execCtx.FixAttempts > 0 && execCtx.Article != "" {
		if err := r.recordRevisedDraft(ctx, execCtx, taskID); err != nil {
			slog.Warn("artifact recorder: failed to record revised_draft", "error", err, "trace_id", execCtx.TraceID)
			errs = append(errs, err)
		}
	}

	// 7. Memory context — injected preference memories
	if execCtx.MemoryContext != nil {
		if err := r.recordMemoryContext(ctx, execCtx, taskID); err != nil {
			slog.Warn("artifact recorder: failed to record memory_context", "error", err, "trace_id", execCtx.TraceID)
			errs = append(errs, err)
		}
	}

	if len(errs) > 0 {
		return fmt.Errorf("recorded %d artifacts with %d errors: %v", len(errs), len(errs), errs[0])
	}

	slog.Info("artifact recorder: all artifacts recorded",
		"trace_id", execCtx.TraceID,
		"task_id", taskID,
		"search_results", len(execCtx.SearchResults),
		"has_compressed", execCtx.CompressedContext != "",
		"has_outline", execCtx.Outline != nil,
		"article_len", utf8.RuneCountInString(execCtx.Article),
		"has_review", execCtx.ReviewResult != nil,
		"fix_attempts", execCtx.FixAttempts,
		"has_memory", execCtx.MemoryContext != nil,
	)
	return nil
}

// recordSourcePack records the full search results as a source_pack artifact.
func (r *ArtifactRecorder) recordSourcePack(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	content, _ := json.Marshal(map[string]interface{}{
		"count":   len(execCtx.SearchResults),
		"results": execCtx.SearchResults,
		"query":   execCtx.UserInput,
	})
	return r.createAndApprove(ctx, taskID, ArtifactSourcePack, string(content), "research_agent")
}

// recordResearchBrief records the compressed context and writing task info.
func (r *ArtifactRecorder) recordResearchBrief(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	data := map[string]interface{}{
		"compressed_context": execCtx.CompressedContext,
	}
	if execCtx.WritingTask != nil {
		data["topic"] = execCtx.WritingTask.Topic
		data["search_queries"] = execCtx.WritingTask.SearchQueries
		data["primary_search_query"] = execCtx.WritingTask.PrimarySearchQuery
		data["word_limit"] = execCtx.WritingTask.WordLimit
	}
	if execCtx.SearchPlan != nil {
		data["search_plan"] = execCtx.SearchPlan
	}
	if execCtx.TaskIntent != nil {
		data["intent"] = execCtx.TaskIntent
	}
	if len(execCtx.UserMaterials) > 0 {
		data["user_materials"] = execCtx.UserMaterials
	}
	content, _ := json.Marshal(data)
	return r.createAndApprove(ctx, taskID, ArtifactResearchBrief, string(content), "research_agent")
}

// recordOutline records the article outline.
func (r *ArtifactRecorder) recordOutline(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	content, _ := json.Marshal(execCtx.Outline)
	return r.createAndApprove(ctx, taskID, ArtifactOutline, string(content), "writing_agent")
}

// recordDraft records the initial article.
func (r *ArtifactRecorder) recordDraft(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	wordCount := utf8.RuneCountInString(execCtx.Article)
	content, _ := json.Marshal(map[string]interface{}{
		"title":      execCtx.ArticleTitle,
		"content":    execCtx.Article,
		"word_count": wordCount,
	})
	return r.createAndApprove(ctx, taskID, ArtifactDraft, string(content), "writing_agent")
}

// recordReviewReport records the post-review quality assessment.
func (r *ArtifactRecorder) recordReviewReport(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	content, _ := json.Marshal(execCtx.ReviewResult)
	return r.createAndApprove(ctx, taskID, ArtifactReviewReport, string(content), "review_agent")
}

// recordRevisedDraft records the article after auto_fix was applied.
func (r *ArtifactRecorder) recordRevisedDraft(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	wordCount := utf8.RuneCountInString(execCtx.Article)
	content, _ := json.Marshal(map[string]interface{}{
		"title":        execCtx.ArticleTitle,
		"content":      execCtx.Article,
		"word_count":   wordCount,
		"fix_attempts": execCtx.FixAttempts,
		"note":         "文章已经过自动修正",
	})
	return r.createAndApprove(ctx, taskID, ArtifactRevisedDraft, string(content), "writing_agent")
}

// recordMemoryContext records the injected user preference memories.
func (r *ArtifactRecorder) recordMemoryContext(ctx context.Context, execCtx *engine.ExecutionContext, taskID string) error {
	content, _ := json.Marshal(map[string]interface{}{
		"memory_context": execCtx.MemoryContext,
	})
	return r.createAndApprove(ctx, taskID, ArtifactType("memory_context"), string(content), "system")
}

// createAndApprove creates an artifact and immediately auto-approves it.
// Writing process artifacts are objective records, not editorial decisions,
// so they are always auto-approved.
func (r *ArtifactRecorder) createAndApprove(ctx context.Context, taskID string, artType ArtifactType, content, producedBy string) error {
	// Calculate content checksum for version verification
	checksum := computeChecksum(content)

	// Build provenance metadata
	provenance := map[string]interface{}{
		"produced_by":   producedBy,
		"produced_at":   time.Now().UTC().Format(time.RFC3339),
		"content_size":  len(content),
		"artifact_type": string(artType),
	}

	// Set retention policy: 90 days for intermediate artifacts, 1 year for drafts
	var retentionUntil *time.Time
	if artType == ArtifactDraft || artType == ArtifactRevisedDraft {
		ret := time.Now().UTC().AddDate(1, 0, 0)
		retentionUntil = &ret
	} else {
		ret := time.Now().UTC().AddDate(0, 0, 90)
		retentionUntil = &ret
	}

	provenanceJSON, _ := json.Marshal(provenance)

	art, err := r.store.CreateArtifactWithVersioning(ctx, SubmitArtifactInput{
		Type:       artType,
		Content:    content,
		ProducedBy: producedBy,
		TokenCost:  0,
	}, taskID, checksum, string(provenanceJSON), retentionUntil)
	if err != nil {
		return fmt.Errorf("create artifact %s: %w", artType, err)
	}
	// Auto-approve the artifact
	if _, err := r.store.ReviewArtifact(ctx, art.ID, ReviewArtifactInput{
		Status:     ArtifactStatusApproved,
		ReviewerID: "system",
		ReviewNote: "写作流程自动记录",
	}); err != nil {
		return fmt.Errorf("approve artifact %s: %w", artType, err)
	}
	return nil
}

// computeChecksum calculates SHA-256 hash of the content
func computeChecksum(content string) string {
	hash := sha256.Sum256([]byte(content))
	return hex.EncodeToString(hash[:])
}
