package engine

import (
	"context"
	"errors"
	"time"
)

// Sentinel errors for exit mechanisms.
var (
	ErrConfirmTimeout     = errors.New("confirm timeout: user inactive")
	ErrClientDisconnected = errors.New("client disconnected")
	ErrBudgetExceeded     = errors.New("token budget exceeded")
	ErrCircuitBreaker     = errors.New("circuit breaker tripped: consecutive LLM failures")
	ErrQuotaExceeded      = errors.New("LLM API quota exceeded: insufficient balance or credits")
)

// ExecutionStatus represents the current status of an execution.
type ExecutionStatus string

const (
	StatusIdle      ExecutionStatus = "idle"
	StatusRunning   ExecutionStatus = "running"
	StatusPaused    ExecutionStatus = "paused"
	StatusCompleted ExecutionStatus = "completed"
	StatusFailed    ExecutionStatus = "failed"
	StatusCancelled ExecutionStatus = "cancelled"
)

// StepName is the identifier for a pipeline step.
type StepName string

const (
	StepIntent          StepName = "intent"
	StepMemoryGate      StepName = "memory_gate"
	StepQueryPlan       StepName = "query_plan"
	StepSearch          StepName = "search"
	StepRelevance       StepName = "relevance"
	StepOutline         StepName = "outline"
	StepWrite           StepName = "write"
	StepPostReview       StepName = "post_review"
	StepAutoFix          StepName = "auto_fix"
	StepMemoryExtract    StepName = "memory_extract"
	StepChat             StepName = "chat"
	StepCompress         StepName = "compress"
	StepShortTermMemory  StepName = "short_term_memory"
	StepShortTermStore   StepName = "short_term_store"
	StepWorkingMemory    StepName = "working_memory"
)

// StepRecord records the execution of a single step.
type StepRecord struct {
	Step        StepName        `json:"step"`
	Status      string          `json:"status"`
	StartedAt   *time.Time      `json:"started_at,omitempty"`
	CompletedAt *time.Time      `json:"completed_at,omitempty"`
	DurationMs  int64           `json:"duration_ms,omitempty"`
	Result      interface{}     `json:"result,omitempty"`
	Error       string          `json:"error,omitempty"`
}

// WritingTask holds parsed writing task info.
type WritingTask struct {
	Topic              string   `json:"topic"`
	SearchQueries      []string `json:"search_queries"`
	PrimarySearchQuery string   `json:"primary_search_query"`
	WordLimit          int      `json:"word_limit"`
}

// SearchResult is a single search result from any source.
type SearchResult struct {
	Title            string  `json:"title"`
	Snippet          string  `json:"snippet"`
	URL              string  `json:"url,omitempty"`
	Source           string  `json:"source"`
	Relevance        string  `json:"relevance,omitempty"` // strong | medium | weak | conflict
	Score            float64 `json:"score,omitempty"`
	CredibilityScore float64 `json:"credibility_score,omitempty"` // 0.0-1.0, from editorial_source_credibility
	IsMock           bool    `json:"is_mock,omitempty"`          // true if generated by LLM (not real search)
}

// CredibilityLookup provides source credibility scores for search results.
// Implemented by editorial.Store or any other provider.
type CredibilityLookup interface {
	// GetCredibility returns the credibility score (0.0-1.0) for a given domain.
	// Returns 0.5 (neutral) if the domain is not in the database.
	GetCredibility(ctx context.Context, domain string) (float64, error)
}

// SearchPlanEntry is a single entry in the search plan.
type SearchPlanEntry struct {
	Query  string `json:"query"`
	Source string `json:"source"` // zhihu | ima | tavily | tencent | weibo
}

// ReviewIssue is a single issue found in post-review.
type ReviewIssue struct {
	Severity string `json:"severity"` // high | medium | low
	Type     string `json:"type"`
	Message  string `json:"message"`
}

// ReviewResult holds the post-write review results.
type ReviewResult struct {
	Scores          map[string]float64 `json:"scores"`
	Issues          []ReviewIssue       `json:"issues"`
	Passed          bool                `json:"passed"`
	TitleSuggestion string              `json:"title_suggestion,omitempty"` // 标题独立评审给出的建议标题（供 AutoFixStep 使用）
}

// OutlineItem is a single point in the outline.
type OutlineItem struct {
	Point string `json:"point"`
	Type  string `json:"type"` // opening | argument | conclusion
}

// OutlineData holds the outline for guided mode.
type OutlineData struct {
	Title   string        `json:"title"`
	Outline []OutlineItem `json:"outline"`
}

// ExecutionContext holds all state for a single writing execution.
type ExecutionContext struct {
	TraceID       string         `json:"trace_id"`
	UserID        string         `json:"user_id"`
	SessionID     string         `json:"session_id"`
	StyleSlug     string         `json:"style_slug"`
	Mode          string         `json:"mode"` // auto | writing | guided | polish
	UserInput     string         `json:"user_input"`
	NormalizedInput string       `json:"normalized_input"`
	UserMaterials []string       `json:"user_materials"`
	WordLimit     int            `json:"word_limit"`

	// Populated during execution
	TaskIntent    *TaskIntent     `json:"task_intent,omitempty"`
	WritingTask   *WritingTask    `json:"writing_task,omitempty"`
	SearchPlan    []SearchPlanEntry `json:"search_plan,omitempty"`
	SearchResults []SearchResult  `json:"search_results,omitempty"`
	Outline       *OutlineData    `json:"outline,omitempty"`
	Article        string          `json:"article,omitempty"`
	ArticleTitle   string          `json:"article_title,omitempty"`
	ReviewResult   *ReviewResult  `json:"review_result,omitempty"`
	// ReasoningContent stores the model's chain-of-thought from thinking mode.
	// Accumulated during the WriteStep and persisted to the trace for historical replay.
	ReasoningContent string       `json:"reasoning_content,omitempty"`

	// Memory context (populated by MemoryGateStep)
	MemoryContext interface{}    `json:"memory_context,omitempty"`

	// Short-term memory: conversation history (populated by ShortTermMemoryStep)
	ConversationHistory interface{} `json:"conversation_history,omitempty"`

	// Working memory: incremental summary + stochastic state
	WorkingSummary    interface{} `json:"working_summary,omitempty"`
	StochasticState   interface{} `json:"stochastic_state,omitempty"`

	// Entity memory network context (populated by MemoryGateStep)
	EntityContext interface{} `json:"entity_context,omitempty"`

	// ConversationID groups messages in the same conversation session
	ConversationID string `json:"conversation_id,omitempty"`

	// Compressed search context (populated by CompressStep)
	// If set, WriteStep uses this structured brief instead of raw SearchResults,
	// reducing prompt token consumption by ~60% and improving generation quality.
	CompressedContext string `json:"compressed_context,omitempty"`

	// FrozenSearchResults indicates that SearchResults are pre-populated (e.g., from
	// a frozen snapshot for experiments). When true, SearchStep skips its own search.
	FrozenSearchResults bool `json:"frozen_search_results,omitempty"`

	// Execution state
	Status        ExecutionStatus `json:"status"`
	CurrentStep   StepName        `json:"current_step"`
	StepHistory   []StepRecord    `json:"step_history"`
	StartedAt     time.Time       `json:"started_at"`
	PausedAt      *time.Time      `json:"paused_at,omitempty"`

	// Token usage
	TotalTokens   int             `json:"total_tokens"`
	MaxTokens     int             `json:"max_tokens,omitempty"` // 0 = unlimited

	// Exit mechanism state
	FixAttempts       int  `json:"fix_attempts,omitempty"`
	MaxFixAttempts    int  `json:"max_fix_attempts,omitempty"` // 0 = unlimited
	ConsecutiveLLMFails int `json:"-"`                              // circuit breaker counter
	MaxLLMFails       int  `json:"-"`                              // circuit breaker threshold
	ConfirmTimeout    time.Duration `json:"-"`                    // await_input timeout (0 = no timer)

	// Control channels
	pauseCh       chan struct{}
	resumeCh      chan struct{}
	cancelCh      chan struct{}
	confirmCh     chan map[string]interface{}
	disconnectCh  chan struct{} // closed when WS client disconnects
}

// TaskIntent holds the result of intent classification.
type TaskIntent struct {
	TaskMode          string  `json:"taskMode"` // writing | polish | chat | shorten | expand | extract_points
	Confidence        float64 `json:"confidence"`
	Source            string  `json:"source"` // rules | llm
	NormalizedInput   string  `json:"normalizedInput"`
}

// NewExecutionContext creates a new context for a writing execution.
func NewExecutionContext(traceID, userID, message string) *ExecutionContext {
	return &ExecutionContext{
		TraceID:     traceID,
		UserID:      userID,
		UserInput:   message,
		Status:      StatusIdle,
		StartedAt:   time.Now(),
		StepHistory: []StepRecord{},
		pauseCh:     make(chan struct{}, 1),
		resumeCh:    make(chan struct{}, 1),
		cancelCh:    make(chan struct{}, 1),
		confirmCh:   make(chan map[string]interface{}, 1),
		disconnectCh: make(chan struct{}),
	}
}

// Pause signals the context to pause.
func (ctx *ExecutionContext) Pause() {
	select {
	case ctx.pauseCh <- struct{}{}:
	default:
	}
}

// Resume signals the context to resume.
func (ctx *ExecutionContext) Resume() {
	select {
	case ctx.resumeCh <- struct{}{}:
	default:
	}
}

// Cancel signals the context to cancel.
func (ctx *ExecutionContext) Cancel() {
	select {
	case ctx.cancelCh <- struct{}{}:
	default:
	}
}

// ConfirmOutline sends confirmed outline data to the context.
func (ctx *ExecutionContext) ConfirmOutline(data map[string]interface{}) {
	select {
	case ctx.confirmCh <- data:
	default:
	}
}

// IsCancelled checks if the context has been cancelled.
func (ctx *ExecutionContext) IsCancelled() bool {
	select {
	case <-ctx.cancelCh:
		return true
	default:
		return false
	}
}

// CheckPause checks if a pause has been requested and blocks until resumed.
// If a pause occurs, it emits Paused/Resumed events via the emitter.
func (ctx *ExecutionContext) CheckPause(ctxGo context.Context, emitter EventEmitter, step StepName) error {
	select {
	case <-ctx.pauseCh:
		now := time.Now()
		ctx.PausedAt = &now
		ctx.Status = StatusPaused
		if emitter != nil {
			emitter.Paused(step, nil)
		}
		// Wait for resume or cancel
		select {
		case <-ctx.resumeCh:
			ctx.Status = StatusRunning
			ctx.PausedAt = nil
			if emitter != nil {
				emitter.Resumed(step)
			}
		case <-ctx.cancelCh:
			return context.Canceled
		case <-ctxGo.Done():
			return ctxGo.Err()
		}
	case <-ctx.cancelCh:
		return context.Canceled
	case <-ctxGo.Done():
		return ctxGo.Err()
	default:
	}
	return nil
}

// WaitForConfirm blocks until the user confirms the outline.
// A confirm timeout is applied to prevent indefinite blocking.
func (ctx *ExecutionContext) WaitForConfirm(ctxGo context.Context) (map[string]interface{}, error) {
	return ctx.WaitForConfirmWithTimeout(ctxGo, 0)
}

// WaitForConfirmWithTimeout blocks until the user confirms or the timeout elapses.
// If timeout is 0, no additional timer is used (relies on ctxGo for cancellation).
func (ctx *ExecutionContext) WaitForConfirmWithTimeout(ctxGo context.Context, timeout time.Duration) (map[string]interface{}, error) {
	var timer *time.Timer
	var timerC <-chan time.Time
	if timeout > 0 {
		timer = time.NewTimer(timeout)
		defer timer.Stop()
		timerC = timer.C
	}

	select {
	case data := <-ctx.confirmCh:
		return data, nil
	case <-ctx.cancelCh:
		return nil, context.Canceled
	case <-ctxGo.Done():
		return nil, ctxGo.Err()
	case <-ctx.disconnectCh:
		return nil, ErrClientDisconnected
	case <-timerC:
		return nil, ErrConfirmTimeout
	}
}

// ─── Exit Mechanism Helpers ──────────────────────────────

// CheckBudget returns true if the token budget has been exceeded.
// Returns false if MaxTokens is 0 (unlimited) or not yet reached.
func (ctx *ExecutionContext) CheckBudget() bool {
	return ctx.MaxTokens > 0 && ctx.TotalTokens >= ctx.MaxTokens
}

// SignalDisconnect marks the client as disconnected.
// Safe to call multiple times — uses sync.Once semantics via channel close.
func (ctx *ExecutionContext) SignalDisconnect() {
	select {
	case <-ctx.disconnectCh:
		// already closed
	default:
		close(ctx.disconnectCh)
	}
}

// IsDisconnected checks if the client has disconnected.
func (ctx *ExecutionContext) IsDisconnected() bool {
	select {
	case <-ctx.disconnectCh:
		return true
	default:
		return false
	}
}

// RecordLLMFailure increments the consecutive LLM failure counter.
// Returns true if the circuit breaker has tripped.
func (ctx *ExecutionContext) RecordLLMFailure() bool {
	ctx.ConsecutiveLLMFails++
	return ctx.MaxLLMFails > 0 && ctx.ConsecutiveLLMFails >= ctx.MaxLLMFails
}

// RecordLLMSuccess resets the consecutive LLM failure counter.
func (ctx *ExecutionContext) RecordLLMSuccess() {
	ctx.ConsecutiveLLMFails = 0
}

// CheckFixLimit returns true if the max fix attempts have been reached.
func (ctx *ExecutionContext) CheckFixLimit() bool {
	return ctx.MaxFixAttempts > 0 && ctx.FixAttempts >= ctx.MaxFixAttempts
}
